# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dea2a009567d8b0b56fcf460552fdfe66cbf16092811283ef061f1d72a6494782c0946cc1274003aa914ec4c380607a29ef8e956c2cab7d5e9c210d6e18a8ffe

test:
  secret_key_base: f20bca7243135baac21eaaa35bab9fd0f4f803f9ad86177cfffc69aea0e4f7da2caeb40bd353cdd153ad8a0cc7209d03363d16c0d6b1f3cd1499b10ac223222d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
